# Generated by Django 2.0.7 on 2018-07-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoConfigInfos',
            fields=[
                ('server_id', models.BigAutoField(db_column='server_ID', primary_key=True, serialize=False)),
                ('server_num', models.CharField(max_length=50)),
                ('board', models.CharField(max_length=50)),
                ('cpu', models.CharField(max_length=50)),
                ('memory_bank', models.CharField(max_length=50)),
                ('hard_disk', models.CharField(max_length=50)),
                ('raid', models.CharField(max_length=50)),
                ('vga', models.CharField(max_length=50)),
                ('gpu', models.CharField(max_length=50)),
                ('hba', models.CharField(max_length=50)),
                ('net_card', models.CharField(max_length=50)),
                ('fc_card', models.CharField(max_length=50)),
                ('inspect_time', models.DateField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'auto_config_infos',
                'managed': False,
            },
        ),
    ]
